db:
  image: postgres
web:
  build: .
  env_file: .env
  command: python manage.py runserver 0.0.0.0:5000
  working_dir: /code/franklin
  volumes:
    - .:/code
  ports:
    - "5000:5000"
  links:
    - db
