db:
  image: postgres
web:
  build: .
  env_file: .env
  working_dir: /code/franklin
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
